CREATE TABLE item_categories (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category TEXT NOT NULL
);

INSERT INTO item_categories 
  (category) 
  VALUES 
  ('Grain'), 
  ('Meat'), 
  ('Fish'), 
  ('Vegetable'), 
  ('Fruit'), 
  ('Seasoning'), 
  ('Sauce'), 
  ('Baking'), 
  ('Sweets'), 
  ('Misc');