CREATE TABLE user_pantry_items (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  item_name TEXT NOT NULL,
  item_category INTEGER REFERENCES item_categories(id),
  user_id INTEGER REFERENCES gliss_users(id) ON DELETE CASCADE,
  date_created TIMESTAMPTZ NOT NULL DEFAULT now()
);
